### ISSUE TITLE
Cannot install on linux: Failed to Extract, Manifest not found in zip archive

### ISSUE THREAD

**Issue by terminatorbs** [PacificEngine/OW_CheatsMod#5]
Trying to install this mod on Linux using the outer wilds mod manager won't work. 

According to 226457179085996034 on discord, it's due to this: https://github.com/ow-mods/ow-mod-man/blob/main/ARCHITECTURE.md#note-about-certain-mods-on-linux

edit to add a quick summary of above link:
the powershell module Compress-Archive puts \ into file paths within archives, going directly against spec. the author recommends using a different zip library, and mentions a [prebuilt action](https://github.com/ow-mods/ow-mod-template/blob/main/templates/Outer-Wilds-Mod-Template/parent-stuff/.github/workflows/release.yml) for automated releases.

For anyone looking for a cheats mod while this one isn't working, Cheat and Debug Menu works for me.

**Comment by colibris79** [comment]
Same here. All the other mods are working fine. Tried with previous of the mod and also with flatpak and appimage versions fo the Mod Manager. Same result
Also using Cheat and Debug Menu instead as well

**Comment by t-wolfeadam** [comment]
Besides the recommendation to use the other "Cheat and Debug Menu" mod, here's instructions for how to fix this:

1. Download the zip
2. Extract the 3 files ("PacificEngine.OW_CheatsMod\PacificEngine.OW_CheatsMod.dll", ...)
4. Remove the directory name from all the files ("PacificEngine.OW_CheatsMod.dll", ...)
5. Select all 3 files, compress to a zip file, rename to "PacificEngine.OW_CheatsMod.zip"
6. Go into OWML and add a new mod from a zip file, choose your updated zip file

**Comment by salomj** [comment]
Fixed in 0.7.5
